config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"

  resources :categories
  resources :posts
  resources :sessions
  resources :users
 

  
  get 'signup' => 'users#new', :as => :signup

  get 'logout' => 'sessions#destroy', :as => :logout

  get 'login' => 'sessions#new', :as => :login

end

app/views/shared/_categories.html.erb
<div class="side_links">

  <% if session[:user_id] %>
    <p class="user_name">Logged in | 
    <%= link_to 'Log Out', logout_path %>
    <br>
    <%= link_to 'New Post', new_post_path %></p>
    <%= link_to 'Private Posts', "#" %>
  <% end -%>
  <br>
  <% if @current_public_post %>
    <%= link_to "Latest_post", post_path(@current_public_post) %></br>
  <% end %>
</div>

<h3>Categories  
<span>
<% if logged_in? %>
  <%= link_to ">> New category", new_category_path, :class => "small" %>
<% end -%>
</span>
</h3>
<hr>
<% @categories.each do |c| %>
  <div class="category">
    <h5>
      <span class="fa-stack fa">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-<%= c.fonticon %> fa-stack-1x fa-inverse"></i>
      </span>
        <span class="catName"><%= c.name %></span>
        <span class="badge">
          <%= c.posts.count %>
        </span>
    </h5>
    <% c.posts.each do |category_post| %>
      <ul>
        <li><%= link_to category_post.title, post_path(category_post) %></li>  
      </ul>
    <% end -%>
  </div>
<% end -%>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container">
      <div class="footer">
        <div class="content">

          <p><%= link_to image_tag("logo.png", width: "70", class: "logo"), "http://www.diligentagility.com" %> <span class="ftext"> <span class="dagreen">diligent</span><span class="dablue">agility</span><small class="copyright"> - timludi - Copyright &copy; 2010 - 2015</small></span></p>

        </div>
      </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<!-- ******HEADER****** --> 
  <header id="top" class="header navbar-fixed-top">  
      <div class="container">            
          <h1 class="logo pull-left">
              <a class="scrollto" href="#promo">
                  <%= link_to image_tag("logo.png", class: "logo-image"), root_path %>
                  <span class="logo-title"><%= link_to "diligent agility", root_path %></span>
              </a>
          </h1><!--//logo-->              
          <nav id="main-nav" class="main-nav navbar-right" role="navigation">
              
              <div class="navbar-header">
                  <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button><!--//nav-toggle-->
              </div><!--//navbar-header--> 

              <div class="navbar-collapse collapse" id="navbar-collapse">
                  <ul class="nav navbar-nav">
                    <!-- <li class="active nav-item sr-only"><a class="scrollto" href="#promo">Home</a></li> -->
                    <li class="active nav-item"><%= link_to "Home", root_path %></li>
                    <li class="nav-item"><%= link_to "Posts", posts_path %></li>
                    <% if logged_in? %>
                      <li class="nav-item"><%= link_to "Logout", logout_path %> </li>
                    <% else %>
                      <li class="nav-item"><%= link_to "Login", login_path %> </li>
                    <% end -%>
                  </ul><!--//nav-->
              </div><!--//navabr-collapse-->
          </nav><!--//main-nav-->           
      </div>
  </header><!--//header-->