config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"

  resources :categories
  resources :posts
  resources :sessions
  resources :users
 

  
  get 'signup' => 'users#new', :as => :signup

  get 'logout' => 'sessions#destroy', :as => :logout

  get 'login' => 'sessions#new', :as => :login

end

app/models/post.rb
class Post < ActiveRecord::Base
  # default_scope {where('created_at DESC')}
  scope :latest, -> {order(:updated_at => :desc)}
  belongs_to :category
  belongs_to :user
  #belongs_to :archive

  def read_post(title)
    @read = "This is from the post, #{title}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :check_if_logged_in, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_categories

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(:updated_at => :desc)
    # @current_public_post = Post.where("status = '0'").last
    if Post.count != 0 
     @current_public_post = Post.last
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if Post.count != 0 
     @current_public_post = Post.last
    end
  end

  # GET /posts/new
  def new
    # @post = Post.new
    @user = User.find(session[:user_id])
    @post = @user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = User.find(session[:user_id])
    @post = @user.posts.build(post_params) # use build with nested models
    # @post = @user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id, :user_id, :status, :featuretext, :fonticon, :postimageurl)
    end

    def check_if_logged_in
      unless logged_in?
        render_404 
      end
    end

    def render_404
      respond_to do |format|
        format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
        format.xml  { head :not_found }
        format.any  { head :not_found }
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container offset-header">

<%= form_for(@post) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => "50" %>
    <span class="actions center"><%= f.submit %></span>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :size => "100x20" %>
  </div>
  <div class="field">
    <%= f.label :feature_text %><br>
    <%= f.text_area :featuretext, :size => "100x10" %>
  </div>
  <div class="field">
    <%= f.label :font_icon %><br>
    <%= f.text_field :fonticon %>
  </div>
  <div class="field">
    <%= f.label :post_image %><br>
    <%= f.text_field :postimageurl %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select(:category_id, Category.all.collect {|c|
         [c.name, c.id]} , {:prompt => "select (nothing yet)"}) %>
         <%= link_to 'Add Category', new_category_path %>
  </div>
  <div class="field">
    <%= f.label :Private_post %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Editing Post</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container offset-header">
  <div class="row">
    <div class="col-sm-8">

      <div class="blog-header">
        <h2 class="blog-title baseGreen">
        <span class="icon">
            <i class="fa fa-book"></i>
          </span>
          All Posts
        </h2>
        
      </div>
      <% @posts.each do |p| %>
        <div class="primary">
           <div class="card_post_wrapper">
            <div class="card_post">
              <div class="card_body">
              <h2 class="card_title"><%= link_to p.title, post_path(p) %></h2>
              <h5 class="small">(<%= p.category.name %>)</h5>
              <hr>
                <span class="small">
                  <% if session[:user_id] %>
                    <%= link_to ' Edit ', edit_post_path(p)  %>
                    <%= link_to '| Delete', p, :confirm => 'Are you sure?', :method => :delete %>
                  <% end -%>
                </span>
             
                <p class="small"><%= p.created_at.strftime("%B %d, %Y")
            %></p>
                <%= markdown(p.body) %>

                <% if session[:user_id] %>
                  <%= link_to ' Edit ', edit_post_path(p)  %>
                  <%= link_to '| Delete', p, :confirm => 'Are you sure?', :method => :delete %>
                <% end -%>
                <br />
                <hr />
            
              </div>
            </div>
          </div>
        </div> <!-- end primary div -->
      <% end -%>
    </div>
 
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
      <div class="secondary">
        <!-- categories go here -->
        <%= render "shared/categories" %>
      </div>
    </div>
 </div>    
</div>

app/views/posts/new.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<!--   <div class="row">
    <div class="col-sm-12"> -->
      <h1>New Post</h1>

      <%= render 'form' %>

      <%= link_to 'Back', posts_path %>
<!--     </div>
  </div> -->
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<!-- <section id="promo" class="promo section offset-header has-pattern"> -->
<div class="container offset-header">
  <div class="row">
    <div class="col-sm-8">

      <div class="blog-header">
        <h2 class="blog-title baseGreen">
          <span class="icon">
            <i class="fa fa-<%= @post.category.fonticon %>"></i>
          </span>
          <%= @post.category.name %>
        </h2>
        <!-- <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p> -->
      </div>

      <div class="primary">
        <div class="post card_post_wrapper">
          <div class="card_post">
            <div class="card_body">
              <h3 class="card_title"><%= @post.title %>
                <% unless @post.status == 0  %>
                  <span id="small"> (Private Post)</span>
                <% end -%>
              </h3>
              <p class="small"><%= @post.updated_at.strftime("%B %d, %Y") %></p>
              <span class="small">
                <% if session[:user_id] %>
                  <%= link_to ' Edit ', edit_post_path(@post)  %>
                  <%= link_to '| Delete', @post, :confirm => 'Are you sure?', :method => :delete %>
                <% end -%>
              </span>
              <hr>
         
              <%= markdown(@post.body) %>

              <br />
              <hr />
              <span class="small">
                <% if session[:user_id] %>
                  <%= link_to ' Edit ', edit_post_path(@post)  %>
                  <%= link_to '| Delete', @post, :confirm => 'Are you sure?', :method => :delete %>
                <% end -%>
              </span>
            </div>
          </div>
        </div>
        <!-- link_to "Previous Posts", archives_path %> -->
      </div> <!-- end primary div -->

    </div> <!-- end col-8 div -->

 
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
      <div class="secondary">
        <%= render "shared/categories" %>
      </div>
    </div>

  </div>  <!-- end row div -->
  
</div> <!-- end container div -->
<!-- </section> -->